-- HR Payroll Portal Database Schema
-- SQLite Database
-- This schema is auto-generated by SQLAlchemy on first run
-- Provided here for reference

-- ============ Users Table ============
-- Stores both HR admins and employees
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('hr', 'employee')),
    emp_id VARCHAR(50) UNIQUE,  -- Employee ID from Excel (NULL for HR)
    can_login BOOLEAN DEFAULT FALSE,  -- Employees can login only after approval
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ============ Employees Table ============
-- Employee details extracted from Excel upload
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    emp_id VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    designation VARCHAR(255),
    department VARCHAR(255),
    email VARCHAR(255),
    basic_da FLOAT DEFAULT 0,
    hra FLOAT DEFAULT 0,
    other_allowances FLOAT DEFAULT 0,
    gross_salary FLOAT DEFAULT 0,
    batch_id INTEGER REFERENCES payroll_batches(id),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ============ Payroll Batches Table ============
-- Monthly payroll processing batches
CREATE TABLE IF NOT EXISTS payroll_batches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    month VARCHAR(50) NOT NULL,  -- e.g., "January 2026"
    excel_file_path VARCHAR(500),
    status VARCHAR(20) NOT NULL CHECK (status IN ('draft', 'generated', 'approved', 'rejected')) DEFAULT 'draft',
    total_employees INTEGER DEFAULT 0,
    total_amount FLOAT DEFAULT 0,
    approved_by INTEGER REFERENCES users(id),
    approved_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ============ Payslips Table ============
-- Individual payslip records
CREATE TABLE IF NOT EXISTS payslips (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER REFERENCES users(id),
    employee_id INTEGER REFERENCES employees(id) NOT NULL,
    batch_id INTEGER REFERENCES payroll_batches(id) NOT NULL,
    
    -- Employee Info
    emp_id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    designation VARCHAR(255),
    month VARCHAR(50) NOT NULL,
    
    -- Attendance
    present_days FLOAT DEFAULT 0,
    approved_paid_leaves FLOAT DEFAULT 0,
    lop_days FLOAT DEFAULT 0,
    payable_days FLOAT DEFAULT 0,
    remaining_leaves FLOAT DEFAULT 0,
    
    -- Earnings
    basic_da FLOAT DEFAULT 0,
    hra FLOAT DEFAULT 0,
    other_allowances FLOAT DEFAULT 0,
    gross FLOAT DEFAULT 0,
    encashment FLOAT DEFAULT 0,
    
    -- Deductions
    pf FLOAT DEFAULT 0,
    esi FLOAT DEFAULT 0,
    pt FLOAT DEFAULT 0,
    tds FLOAT DEFAULT 0,
    total_deductions FLOAT DEFAULT 0,
    
    -- Net
    net_pay FLOAT DEFAULT 0,
    
    -- PDF
    pdf_path VARCHAR(500),
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ============ Policies Table ============
-- Payroll policy settings
CREATE TABLE IF NOT EXISTS policies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pf_rate FLOAT DEFAULT 0.12,
    pf_cap FLOAT DEFAULT 1800,
    esi_employee_rate FLOAT DEFAULT 0.0075,
    esi_threshold FLOAT DEFAULT 21000,
    pt_amount FLOAT DEFAULT 200,
    leave_encashment BOOLEAN DEFAULT FALSE,
    encash_max_days INTEGER DEFAULT 10,
    policy_text TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ============ Indexes ============
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_emp_id ON users(emp_id);
CREATE INDEX IF NOT EXISTS idx_employees_emp_id ON employees(emp_id);
CREATE INDEX IF NOT EXISTS idx_employees_batch_id ON employees(batch_id);
CREATE INDEX IF NOT EXISTS idx_payslips_emp_id ON payslips(emp_id);
CREATE INDEX IF NOT EXISTS idx_payslips_batch_id ON payslips(batch_id);
CREATE INDEX IF NOT EXISTS idx_payslips_user_id ON payslips(user_id);
CREATE INDEX IF NOT EXISTS idx_payroll_batches_status ON payroll_batches(status);
